name:                packed-memory-containers
version:             0.1.0.0
github:              "fizruk/packed-memory-containers"
license:             BSD3
author:              "Nikolai Kudasov, Niyaz Fahretdinov, Azat Sultanov"
maintainer:          "n.kudasov@innopolis.ru"
copyright:           "2019-2020 Innopolis University"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Cache-oblivious efficient packed-memory containers
category:            Data

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/fizruk/packed-memory-containers#readme>

custom-setup:
  dependencies:
    - base
    - Cabal
    - cabal-doctest >=1.0.2 && <1.1

dependencies:
- base >= 4.7 && < 5
- vector
- primitive
- containers

library:
  source-dirs: src

executables:
  packed-memory-containers-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - packed-memory-containers

  vector-interactive:
    main: VectorInteractive.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -main-is VectorInteractive
    dependencies:
    - packed-memory-containers

  vector-read:
    main: VectorRead.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -main-is VectorRead
    dependencies:
    - packed-memory-containers

  vector-update:
    main: VectorUpdate.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -main-is VectorUpdate
    dependencies:
    - packed-memory-containers

  vector-grow:
    main: VectorGrow.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -main-is VectorGrow
    dependencies:
    - packed-memory-containers

  vector-populate:
    main: VectorPopulate.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -main-is VectorPopulate
    dependencies:
    - packed-memory-containers

tests:
  spec:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - packed-memory-containers
    - QuickCheck

  doctests:
    source-dirs: test
    main: doctests.hs
    other-modules: []
    dependencies:
    - base
    - doctest
    - Glob
    - QuickCheck
    - template-haskell
